<?php

namespace DoctrineProxies\__CG__\addventure;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Session extends \addventure\Session implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'addventure\\Session' . "\0" . 'session_id', '' . "\0" . 'addventure\\Session' . "\0" . 'ip_address', '' . "\0" . 'addventure\\Session' . "\0" . 'user_agent', '' . "\0" . 'addventure\\Session' . "\0" . 'last_activity', '' . "\0" . 'addventure\\Session' . "\0" . 'user_data');
        }

        return array('__isInitialized__', '' . "\0" . 'addventure\\Session' . "\0" . 'session_id', '' . "\0" . 'addventure\\Session' . "\0" . 'ip_address', '' . "\0" . 'addventure\\Session' . "\0" . 'user_agent', '' . "\0" . 'addventure\\Session' . "\0" . 'last_activity', '' . "\0" . 'addventure\\Session' . "\0" . 'user_data');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Session $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getSession_id()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getSession_id();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSession_id', array());

        return parent::getSession_id();
    }

    /**
     * {@inheritDoc}
     */
    public function getIp_address()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIp_address', array());

        return parent::getIp_address();
    }

    /**
     * {@inheritDoc}
     */
    public function getUser_agent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser_agent', array());

        return parent::getUser_agent();
    }

    /**
     * {@inheritDoc}
     */
    public function getLast_activity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLast_activity', array());

        return parent::getLast_activity();
    }

    /**
     * {@inheritDoc}
     */
    public function getUser_data()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser_data', array());

        return parent::getUser_data();
    }

    /**
     * {@inheritDoc}
     */
    public function setSession_id($session_id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSession_id', array($session_id));

        return parent::setSession_id($session_id);
    }

    /**
     * {@inheritDoc}
     */
    public function setIp_address($ip_address)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIp_address', array($ip_address));

        return parent::setIp_address($ip_address);
    }

    /**
     * {@inheritDoc}
     */
    public function setUser_agent($user_agent)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser_agent', array($user_agent));

        return parent::setUser_agent($user_agent);
    }

    /**
     * {@inheritDoc}
     */
    public function setLast_activity($last_activity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLast_activity', array($last_activity));

        return parent::setLast_activity($last_activity);
    }

    /**
     * {@inheritDoc}
     */
    public function setUser_data($user_data)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser_data', array($user_data));

        return parent::setUser_data($user_data);
    }

}
