<?php
namespace addventure;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-06-02 at 00:08:43.
 */
class CommentTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Comment
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Comment;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers addventure\Comment::getId
     * @todo   Implement testGetId().
     */
    public function testGetId()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers addventure\Comment::getCreated
     * @todo   Implement testGetCreated().
     */
    public function testGetCreated()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers addventure\Comment::getText
     * @todo   Implement testGetText().
     */
    public function testGetText()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers addventure\Comment::getEpisode
     * @todo   Implement testGetEpisode().
     */
    public function testGetEpisode()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers addventure\Comment::getAuthorName
     * @todo   Implement testGetAuthorName().
     */
    public function testGetAuthorName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers addventure\Comment::setId
     * @todo   Implement testSetId().
     */
    public function testSetId()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers addventure\Comment::setCreated
     * @todo   Implement testSetCreated().
     */
    public function testSetCreated()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers addventure\Comment::setText
     * @todo   Implement testSetText().
     */
    public function testSetText()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers addventure\Comment::setEpisode
     * @todo   Implement testSetEpisode().
     */
    public function testSetEpisode()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers addventure\Comment::setAuthorName
     * @todo   Implement testSetAuthorName().
     */
    public function testSetAuthorName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers addventure\Comment::toAtom
     * @todo   Implement testToAtom().
     */
    public function testToAtom()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers addventure\Comment::toJson
     * @todo   Implement testToJson().
     */
    public function testToJson()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers addventure\Comment::toRss
     * @todo   Implement testToRss().
     */
    public function testToRss()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers addventure\Comment::toSmarty
     * @todo   Implement testToSmarty().
     */
    public function testToSmarty()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
